# Generated by Django 3.1.1 on 2020-09-08 11:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='word_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 8, 16, 28, 7, 625246), verbose_name='date added'),
            preserve_default=False,
        ),
    ]
