# Generated by Django 3.1.1 on 2020-09-15 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydic', '0005_auto_20200915_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='word_text',
            field=models.CharField(max_length=50, unique=True, verbose_name='Word'),
        ),
    ]
