# Generated by Django 3.1.1 on 2020-09-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydic', '0006_auto_20200915_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='word_text',
            field=models.CharField(max_length=50, verbose_name='Word'),
        ),
    ]
